title: Tabbed Cards
views:
  - title: Map First
    cards:
      - type: custom:tabbed-card
        tabs:
          - attributes:
              label: Map Tab
            card:
              type: map
              title: Map
              entities:
                - device_tracker.demo_paulus
                - device_tracker.demo_anne_therese
          - attributes:
              label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: humidifier
                  entity: humidifier.dehumidifier
                - type: humidifier
                  entity: humidifier.humidifier
                - type: humidifier
                  entity: humidifier.hygrostat
          - attributes:
              label: Button
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
  - title: Map Second
    cards:
      - type: custom:tabbed-card
        tabs:
          - attributes:
              label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: humidifier
                  entity: humidifier.dehumidifier
                - type: humidifier
                  entity: humidifier.humidifier
                - type: humidifier
                  entity: humidifier.hygrostat
          - attributes:
              label: Map Tab
            card:
              type: map
              title: Map
              entities:
                - device_tracker.demo_paulus
                - device_tracker.demo_anne_therese
          - attributes:
              label: Button
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
  - title: Solo
    cards:
      - type: custom:tabbed-card
        tabs:
          - attributes:
              label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: humidifier
                  entity: humidifier.dehumidifier
                - type: humidifier
                  entity: humidifier.humidifier
                - type: humidifier
                  entity: humidifier.hygrostat
          - attributes:
              label: Test Map
            card:
              type: map
              title: Test Map
              entities:
                - device_tracker.demo_paulus
                - device_tracker.demo_anne_therese
          - attributes:
              label: Thermostat
            card:
              type: thermostat
              name: HVACS
              entity: climate.hvac
          - attributes:
              label: Button
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
          - attributes:
              label: Sensors
            card:
              type: entities
              title: Sensor
              entities:
                - sensor.carbon_dioxide
                - sensor.carbon_monoxide
                - sensor.outside_humidity
                - sensor.outside_temperature
                - sensor.power_consumption
                - sensor.today_energy
          - attributes:
              label: Air Quality
            card:
              type: entities
              title: Air Quality
              entities:
                - air_quality.demo_air_quality_home
                - air_quality.demo_air_quality_office
          - attributes:
              label: Lights
            card:
              type: entities
              title: Light
              entities:
                - light.bed_light
                - light.ceiling_lights
                - light.entrance_color_white_lights
                - light.kitchen_lights
                - light.living_room_rgbww_lights
                - light.office_rgbw_lights
          - attributes:
              label: Binary Sensor
            card:
              type: entities
              title: Binary sensor
              entities:
                - binary_sensor.basement_floor_wet
                - binary_sensor.movement_backyard
          - attributes:
              label: Calendar
            card:
              type: entities
              title: Calendar
              entities:
                - entity: calendar.calendar_1
                  name: "1"
                - entity: calendar.calendar_2
                  name: "2"
          - attributes:
              label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: picture-entity
                  entity: camera.demo_camera
                - type: thermostat
                  name: HVACS
                  entity: climate.hvac
                - type: entities
                  title: Calendar
                  entities:
                    - entity: calendar.calendar_1
                      name: "1"
                    - entity: calendar.calendar_2
                      name: "2"
                - type: picture-entity
                  entity: camera.demo_camera_png
  - title: Many
    cards:
      - type: entities
        title: Air Quality
        entities:
          - air_quality.demo_air_quality_home
          - air_quality.demo_air_quality_office
      - type: custom:tabbed-card
        tabs:
          - attributes:
              label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: humidifier
                  entity: humidifier.dehumidifier
                - type: humidifier
                  entity: humidifier.humidifier
                - type: humidifier
                  entity: humidifier.hygrostat
          - attributes:
              label: Test Map
            card:
              type: map
              title: Test Map
              entities:
                - device_tracker.demo_paulus
                - device_tracker.demo_anne_therese
          - attributes:
              label: Thermostat
            card:
              type: thermostat
              name: HVACS
              entity: climate.hvac
          - attributes:
              label: Button
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
          - attributes:
              label: Sensors
            card:
              type: entities
              title: Sensor
              entities:
                - sensor.carbon_dioxide
                - sensor.carbon_monoxide
                - sensor.outside_humidity
                - sensor.outside_temperature
                - sensor.power_consumption
                - sensor.today_energy
          - attributes:
              label: Air Quality
            card:
              type: entities
              title: Air Quality
              entities:
                - air_quality.demo_air_quality_home
                - air_quality.demo_air_quality_office
          - attributes:
              label: Lights
            card:
              type: entities
              title: Light
              entities:
                - light.bed_light
                - light.ceiling_lights
                - light.entrance_color_white_lights
                - light.kitchen_lights
                - light.living_room_rgbww_lights
                - light.office_rgbw_lights
          - attributes:
              label: Binary Sensor
            card:
              type: entities
              title: Binary sensor
              entities:
                - binary_sensor.basement_floor_wet
                - binary_sensor.movement_backyard
          - attributes:
              label: Calendar
            card:
              type: entities
              title: Calendar
              entities:
                - entity: calendar.calendar_1
                  name: "1"
                - entity: calendar.calendar_2
                  name: "2"
          - attributes:
              label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: picture-entity
                  entity: camera.demo_camera
                - type: thermostat
                  name: HVACS
                  entity: climate.hvac
                - type: entities
                  title: Calendar
                  entities:
                    - entity: calendar.calendar_1
                      name: "1"
                    - entity: calendar.calendar_2
                      name: "2"
                - type: picture-entity
                  entity: camera.demo_camera_png
      - type: entities
        title: Button
        entities:
          - button.push
      - type: alarm-panel
        entity: alarm_control_panel.security
  - title: Styled
    cards:
      - type: custom:tabbed-card
        options:
          defaultTabIndex: 1
        styles:
          --mdc-theme-primary: yellow
          --mdc-tab-text-label-color-default: orange
          --mdc-tab-color-default: orange
        attributes:
          label:
          icon: mdi:stop
          isFadingIndicator:
          minWidth:
          isMinWidthIndicator:
          stacked:
          active:
        tabs:
          - styles:
              --mdc-theme-primary: green
              --mdc-tab-text-label-color-default: pink
              --mdc-tab-color-default: pink
            attributes:
              label: Button
              icon: mdi:fire
              isFadingIndicator:
              minWidth:
              isMinWidthIndicator:
              stacked: true
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
          - attributes:
              label: Sensors
              icon: mdi:tree
              isFadingIndicator:
              minWidth:
              isMinWidthIndicator:
              stacked:
            card:
              type: entities
              title: Sensor
              entities:
                - sensor.carbon_dioxide
                - sensor.carbon_monoxide
                - sensor.outside_humidity
                - sensor.outside_temperature
                - sensor.power_consumption
                - sensor.today_energy
          - attributes:
              label: Air Quality
              icon: mdi:play
              isFadingIndicator:
              minWidth:
              isMinWidthIndicator:
              stacked:
            card:
              type: entities
              title: Air Quality
              entities:
                - air_quality.demo_air_quality_home
                - air_quality.demo_air_quality_office
          - card:
              type: entities
              title: Binary sensor
              entities:
                - binary_sensor.basement_floor_wet
                - binary_sensor.movement_backyard
