blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/kinghat/tabbed-card/discussions/new?category=feature-requests
    about: Submit feature requests to our discussion forum.
